In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

False

Sử dụng GPU và Cuda

In [ ]:
torch.cuda.current_device

<function torch.cuda.current_device() -> int>

In [ ]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [ ]:
# Trả về mức sử dụng bộ nhớ gpu hiện tại theo tensors tính bằng byte cho thiết bị
torch.cuda.memory_allocated()


0

In [ ]:
# Trả về bộ nhớ GPU hiện tại đc quản lý bởi bộ phân bổ bộ nhớ đệm theo byte
torch.cuda.memory_cached()

<ipython-input-5-92d5061188e2>:2: FutureWarning: `torch.cuda.memory_cached` has been renamed to `torch.cuda.memory_reserved`
  torch.cuda.memory_cached()


0

Dataset with pytorch


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#
df = pd.read_csv("/content/iris.csv")
df.head()


sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.shape

(150, 5)

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le =  LabelEncoder()
X = df.drop(["variety" ], axis = 1).values
y = le.fit_transform(df["variety"].values)

# chia dữ liệu với test size = 0.2

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

In [ ]:
print(f"train size {len(y_train)}")

train size 120


In [ ]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
# Tính dạo hàm bằng pytorch

# cho y = 2x^4 + x^3 + 3x^2 + 5x + 1

# tính y'




In [ ]:
import torch

In [ ]:
# tạo một tensor với requirments_grad được đặt thành true

x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [ ]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [ ]:
y.grad_fn

In [ ]:
# Thực hiện truyền ngược và tính toán các gradient

y.backward()

In [ ]:
# Kết quả đạo hàm
x.grad

tensor(93.)

In [ ]:
# Bai tap

#Cho y = 5x^6+3x^3+2x^1+x+2x+5x^4+1

# Cho biết độ dốc của đa thức trên tại điểm nào

BTVN 1:

Tạo một tensor có gia trị ban đầu là 2.0

Định nghĩa hàm số và tính gradient

y = x^3 + 2x^2 + 5x + 1

hãy tính dy/dx tại giá trị của x

Dùng phương pháp Gradient Descent với learning rate alpha = 0.1
để cập nhật giá trị x trong 10 vòng lặp

BTVN 2:

Tạo một tập dữ liệu giả lập với x là số giờ học( ngẫu nhiên từ 1 - 10)
và y là số điểm được tính theo công thức y = 3x + 5 + noise

Với noise là một giá trị ngẫu nhiên nhỏ

1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad= true
2. tính MSE
3. Tính gradient
4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình



In [ ]:
# pytorch with tensor

In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
# Chuyển đổi mảng numpy sang tensor pytorch

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [ ]:
x = torch.from_numpy(arr)
print(x)


tensor([1, 2, 3, 4, 5])


In [ ]:
print(x.dtype)

torch.int64


In [ ]:
print(x.type())

torch.LongTensor


In [ ]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


Copying and sharing

In [ ]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [ ]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
# BTVN 3: Giải thích lý do tại sao cho 2 trường hợp trên

In [ ]:
# BTVN 4: bạn hãy giúp thầy về nhà tạo tensor với:
# Empyty
# Zeros
# Ones
# Random
# Reshape với view và view as


# Deadline 16/03/2025